### ISSUE TITLE
3 Issues | Cant Warp to another players warp, /Island Warp returns nothing, Level not updating for warp sign

### ISSUE THREAD

**Issue by iLewisMC** [BentoBoxWorld/Warps#36]
**Issue 1:**
Ive just created a warp on my island called 'Test' (the only island on the a fresh server). The top line turned green and I got the success message in chat but when attemping to use '/island warp Test' I get the error message 'Oh snap! That warp no longer exists!' The only way to access the warp is via the warps GUI. 

**Issue 2:**
'/island warp' & '/is warp'
Return nothing. no error message in chat or in console. 

**Issue 3:**
When first attemping to place my welcome sign I was repeatedly sent a error msg about having to reach level10 on my island before being allowed make a warp sign even though I had placed alot on diamond blocks to boost my level. I then checked my island level using the cmd (and it was almost 200). After preforming the command it did allowed me to place the welcome sign.

**Comment by tastybento** [comment]
Issue 1: Warps are not address by what's written on them, but by the name of the player placing them. So use, `/is warp <your-name>` or use `/is warps` to show the warps available.

Issue 2: This is a known bug that I'm going to fix. To list warps, use /is warps.

Issue 3: You have to do `/is level` to have the system calculate the level, so that's why it worked as soon as you did that.

**Comment by iLewisMC** [comment]
Great. Thank you for your response @tastybento
